### ISSUE TITLE
Please provide your apk somewhere.

### ISSUE THREAD

**Issue by famewolf** [jensstein/oandbackup#11]
F-droid has still not updated to your latest version....some of your changes have been in for a couple weeks or so, so could you provide a binary somewhere we can download?

**Comment by rancidfrog** [comment]
Old issue, but many projects have automatic uploads to release tab, using travis I believe.
It would ve great to have apk also available in release section.

**Comment by ildar** [comment]
@rancidfrog , having multiple apk with different signatures would cause
more problems. Are you sure you need it?

**Comment by rancidfrog** [comment]
It would be nice to have apk available in release section. 
As mentioned, sometimes it takes longer to update on 3rd party sites.
But, I see how different signatures can be a hassle.
However, aren't google play and fdroid versions having different signatures?
So, people who usually use updates from play will still use that, people who use fdroid will use that, and people who like to test or get directly from github ...

The problem exists because fdroid use their own key as "security" against compiling from source...
But, for google and github you could use same keys to sign.

**Comment by ildar** [comment]
AFAIK jensstein decided to not publish this app on Google Play. Fix me if
I'm wrong.
Anyway please respect his decision when he wrote he doesn't upload apk.
Also the readme clearly says:
> an apk build of oandbackup is available on f-droid's servers:
https://f-droid.org/repository/browse/?fdid=dk.jens.backup

Ok?
