### ISSUE TITLE
Highlight disabled packages

### ISSUE THREAD

**Issue by reddit-is-fun** [jensstein/oandbackup#126]
Currently oandbackup doesn't mark the disabled apps in any way, there's no easy way to see if an app is enabled (except they are excluded from backups). Titanium Backup highlights "frozen" apps in blue, I'd like to see something similar.
You can also "disable" apps again if you so desire.

**Comment by jensstein** [comment]
done :) implemented in 3551acf.
i'm not sure what you mean by your last line though. oab can already enable and disable packages. please elaborate.

**Comment by reddit-is-fun** [comment]
@jensstein Thank you. 
By the last sentence I mean that the "disable" option is there also for apps that are already disabled.

**Comment by jensstein** [comment]
yes, both options are displayed because a package can be enabled for some users and disabled for others. and i haven't looked into what it would take to distinguish the package status between the different users. so until i do that or somebody tells me what to do both options will be there at the same time. i wouldn't think it's very complicated to figure out though.
i'll close this issue :)
