### ISSUE TITLE
Errors with saved pages backup in Opera Mini Native 

### ISSUE THREAD

**Issue by gitgt** [jensstein/oandbackup#129]
I get errors with Opera Mini 16 Native on Android 4.4.2:

2016/05/28 - 15:59:51: cp: /storage/sdcard1/oandbackups/com.opera.mini.native/com.opera.mini.native/files/favorite_savedpage:file82799792: Invalid argument [Opera Mini]

2016/05/28 - 15:59:51: cp: /data/data/com.opera.mini.native/files/turboproxy: No such device or address [Opera Mini]

2016/05/28 - 15:59:51: cp: /storage/sdcard1/oandbackups/com.opera.mini.native/com.opera.mini.native/files/favorite_savedpage:file39143607: Invalid argument [Opera Mini]

Previous Opera Mini 7 Android works.

**Comment by jensstein** [comment]
for the ```invalid argument``` errors i would guess that it's the ```:``` in the filenames. which filesystem does the device you have your backup directory on have? try copying those files manually with ```cp``` and see if escaping the colon helps.
can you see which kind of file ```turboproxy``` is?
and can you check if the app can be restored successfully even with these errors ?

a method for defining a custom list of errors to ignore is on the todo list, so that would handle this if the errors are not fatal.

**Comment by gitgt** [comment]
"for the invalid argument errors i would guess that it's the : in the filenames."
Very likely. Is there a workaround? think these are saved pages in Opera. 

"which filesystem does the device you have your backup directory on have?"
It's SDcard with Fat32.

"try copying those files manually with cp and see if escaping the colon helps."
Copying to the same root devise is possible with X-plore, to SDcard it's not. 

"can you see which kind of file turboproxy is?"
It's 0 Bytes file with Mode: 700. There's something strange,  X-plore doesn't show it's size at all, unlike some other in the same folder for which it says 0.00B. But I could copy it with X-plore.

"and can you check if the app can be restored successfully even with these errors ?"
Yes, it can. Except some saved pages are not restored (only shown with those numbers 82799792...). Some others are correct though.

**Comment by jensstein** [comment]
the problem is that fat32 doesn't support colons in filenames. the only work-around is to rename the file. so that would mean looping over all the files rather than running ```cp -R```, and then keeping a list mapping the renamed files to their original names. i don't know if this might be overkill in relation to the problem it's solving.
the error ignore list is perhaps the most immediate solution. but the other solution may come later. 

the proxy file could be something like a fifo special file. it's hopefully restored by the program itself when it needs it.
