### ISSUE TITLE
Backup to external SD ?

### ISSUE THREAD

**Issue by repsorp** [jensstein/oandbackup#165]
Hi,

Is there any way to backup to an external SD with Android 7.1.2 ?
When trying to I get the following error message:
![error](https://cloud.githubusercontent.com/assets/6297032/25756237/4bc77f3c-31c6-11e7-90d6-97112ac13efd.png)

Thanks

**Comment by willsALMANJ** [comment]
I had some different problems trying to back up to an external sd card. First, oandbackup complained about oandbackup.log being missing until I copied it to the directory on the sd card that I wanted to use. Then it didn't finish the backup. I created folders for each app that contained all of the app data rather than creating zip files. I think oandbackup copies all the data over in a folder and then zips the folder, so it seems like it was not able to zip the data on the sd card for some reason. I couldn't find an error message.

Finally, I tried switching back to using the default location for backups by deleting the path. Then it wouldn't remember my lists of apps for scheduled backups. I ended up reinstalling oandbackup at this point. Maybe I just needed to put the original oandbackup path back in explicitly instead of leaving it blank.

It would be great to be able to back up to an external sd card. One goal of backing up apps for me is to be able to recover from the phone dying, so having the data on a drive that can be moved to a new device is helpful.

**Comment by ildar** [comment]
Please provide your Android version and oandbackup version

**Comment by willsALMANJ** [comment]
Android 7.1.2 (Lineage 14.1) and oandbackup 0.2.12.1 from F-Droid. Has backing up to an external SD card worked for you?

**Comment by ildar** [comment]
No, I didn't see it working with external SD on LA14.1. Though I never
tried hard, AFAIK there was the apk doing that.
