### ISSUE TITLE
Releases on F-Droid are outdated

### ISSUE THREAD

**Issue by DDoSolitary** [jensstein/oandbackup#226]
The latest version available on F-Droid is v0.2.13 while the latest one in this repo is v0.3.4. Pls update it, thanks.

**Comment by gitgt** [comment]
Please no rush. Latest is 0.3.4. And AFAIK F-Droid itself packages those.  So issue can be closed.

**Comment by DDoSolitary** [comment]
Yeah, v0.3.4 is available now :smile:

**Comment by iexos** [comment]
To me, 0.3.4 is a downgrade on F-Droid from 0.3.3 arm64. Are the app versions correct?

**Comment by ildar** [comment]
No, they are not. https://gitlab.com/fdroid/fdroiddata/issues/1366

**Comment by jensstein** [comment]
i use a versioning scheme similar to the one recommended by google here: https://developer.android.com/google/play/publishing/multiple-apks#VersionCodes
they recommend assigning the lowest version code to the universal apk and since fdroid only built some apks for 0.3.3 (not the universal flavour - it had a bug in the build configuration, so they ignored it) you might get a version code downgrade if they now offer you the universal flavour instead of the arm64 flavour. if this is not the case then it might be a bug on my part.
