### ISSUE TITLE
Cannot restore data

### ISSUE THREAD

**Issue by mase76** [jensstein/oandbackup#57]
Hi!
Restoring apk works well. Restoring data after apk shows no error, but also shows no
effect. No app settings. When restoring apk & data or restoring data again, i get the error
": setPermissions error: could not find permissions for /data/data/a2dp.Vol" for example.
Also for every other app restore.
I am using CM11 nightly without gapps.

**Comment by ildar** [comment]
> could i get you to run this command on your device: busybox stat $packageDir | busybox sed -nr 's|.*Uid: \((.?[0-9]+).*|\1|p'
do you check the busybox plugins in the oandbackup initialization?
I just checked and found that my busybox simply doesn't have `stat/fstat` etc.
Getting the same error: `setPermissions error: could not find permissions for `
and adb log:
> I/oandbackup(24470): restoring: 4pda
> I/oandbackup(24470): getOwnership return: 0
> E/oandbackup(24470): no uid and gid found while trying to set permissions
> I/oandbackup(24470): return: 1 / error

**Comment by jensstein** [comment]
no only the busybox binary itself is checked. i'm not sure it would be a good idea to check for all the individual programs and their flags on each startup but i might include a function to check it manually. i should probably also mentions the busybox programs that are used in the readme under the compilation instructions.
and i have code for an error log reader which will be uploaded sometime soon so that will hopefully give a better way of determining the cause of errors such as these.
