### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by benpye** [jensstein/oandbackup#73]
oandbackup is crashing for me when getting package info, https://github.com/jensstein/oandbackup/blob/master/src/dk/jens/backup/AppInfoHelper.java#L48 appears to be the culprit. 

```
E/AndroidRuntime(19642): FATAL EXCEPTION: Thread-326
E/AndroidRuntime(19642): Process: dk.jens.backup, PID: 19642
E/AndroidRuntime(19642): java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
E/AndroidRuntime(19642): 	at dk.jens.backup.AppInfoHelper.getPackageInfo(AppInfoHelper.java:48)
E/AndroidRuntime(19642): 	at dk.jens.backup.OAndBackup$1.run(OAndBackup.java:105)
E/AndroidRuntime(19642): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  602):   Force finishing activity dk.jens.backup/.OAndBackup```

**Comment by cjeanneret** [comment]
Hello,

It might be good to push some "pre-release" on f-droid, even if there isn't encryption. Currently, we're unable to backup our stuff on, in my case, Lollipops (latest CM-12).
Sure I might use the APK you built, but I'll need to uninstall the version I have, re-install from your APK (due to signature missmatch), re-configure… and do the same stuff once you push the new release on f-droid :(.

You might want to add some "beta" flag if you're unsure of its stability. Will be anyway better than the current version…

Thank you!

Cheers,

C.

**Comment by jensstein** [comment]
actually, encryption is implemented. and don't worry, there will be a release in a relatively short time. i just need to fix a few issues and test it properly with android 5.0.
i know it's cumbersome to have to uninstall to install a non-fdroid version but at least you don't actually have to re-configure. you can just get oab to restore it's own data. just remember to force close it after the restore is done to get the restored data loaded.
i'm not directly in control of the apk on f-droid. they build based on tagged commits in git and i don't really want to tag a release before it can be a proper release. i don't think a beta flag would not make any difference in the f-droid client. especially since oab as a whole should be considered beta quality.
so please have patience a little longer.

**Comment by cjeanneret** [comment]
Heya!

good news, the provided APK (the one from gdrive) works on Lollipop!
Currently doing its backup, I also could restore oandbackup configuration successfully :).

I'll go like that for now on — I'll also try this version on my slimrom device, as it couldn't restore anything due to some right problems (couldn't find right for directory content, something like that).

Cheers,

C.

**Comment by jensstein** [comment]
@cjeanneret great :) please open a new issue on that problem with directory content that you see. you can hopefully find some information in the error log: /sdcard/oandbackups/oandbackup.log
